### ISSUE TITLE
PCF Dev crashes host machine and VMR port 7000 is no longer accessible

### ISSUE THREAD

**Issue by schan-solace** [SolaceLabs/solace-messaging-cf-dev#11]
When PCF Dev crashes the host machine (Mac), on restarting the 3 VMs, the VMR port 7000 is no longer accessible and apps cannot connect to the VMR. VMR logs appear to show everything is fine, so maybe the problem is outside the VMR.

So far, only a recreation of the entire PCF DEV environment solves it

**Comment by PhilippeKhalife** [comment]
I'd like to understand why there is a  crash in the first place if possible. is there any logs/diagnostics done on boot up? How much RAM was in use at the time? If you suspect a RAM size issue, consider using less RAM for PCFDev and since you are using a Mac you may want to consider not creating the cli-tools VM to save RAM, directly use the scripts from solace-messaging-cf-dev/bin , you will need to have the bosh cli and cf cli installed.
Also if not using the cli-tools, you should look at solace-messaging-cf-dev/.profile and use it to make sure you have the necessary setup.
