### ISSUE TITLE
Installing the Solace Service Broker on PCF Dev failed

### ISSUE THREAD

**Issue by anushkapaliwal** [SolaceLabs/solace-messaging-cf-dev#25]
I followed all the steps in order but I am stuck on Deployment Step 2. The installServiceBroker.sh script doesn't run successfully. 

This is the message I received:
Creating service broker solace-messaging as admin...
FAILED
Server error, status code: 502, error code: 270013, message: Service broker dashboard clients could not be modified: The UAA request was invalid

I downloaded v0.27.0 for PCF 1.11.0.

**Comment by PhilippeKhalife** [comment]
The current tile release 1.1.0 is tested and supported up to PCF 1.10.0
There is also a known issue preventing the solace service broker from working under PCF 1.11, this issue is fixed and will be available in the next tile release.

Please use PCFDev plugin 0.26.0 or earlier as they use PCF releases 1.10.0 and earlier ( supported by the solace-messaging tile release )
We will improve the documentation to state a specific version of PCFDev to download for each tile release.

**Comment by PhilippeKhalife** [comment]
No longer an issue, PCF Dev is not in use anymore.
